package api

import "github.com/gin-gonic/gin"

func (s *Server) registerPublicRoutes(r *gin.Engine) {
	r.POST("/api/auth/login", s.login)
	r.POST("/api/auth/password", s.changePassword)
	r.POST("/api/drive/auth/login", s.driveLogin)
}

func (s *Server) registerProtectedRoutes(r *gin.Engine) {
	driveAdmin := r.Group("/api/drive/accounts", s.requireAdmin())
	driveAdmin.GET("", s.listDriveAccounts)
	driveAdmin.POST("", s.createDriveAccount)
	driveAdmin.PUT("/:id", s.updateDriveAccount)
	driveAdmin.DELETE("/:id", s.deleteDriveAccount)
	driveAdmin.POST("/:id/reset-password", s.resetDriveAccountPassword)
	driveAdmin.POST("/:id/recount-used", s.recountDriveAccountUsed)
	driveAdmin.POST("/:id/index/rebuild", s.driveIndexRebuild)
	driveAdmin.GET("/:id/index/status", s.driveIndexStatus)

	driveAPI := r.Group("/api/drive", s.driveAuthMiddleware())
	driveAPI.GET("/files", s.driveListFiles)
	driveAPI.GET("/entries", s.driveListEntries)
	driveAPI.GET("/preview-url", s.drivePreviewURL)
	driveAPI.POST("/folders", s.driveMkdir)
	driveAPI.POST("/rename", s.driveRename)
	driveAPI.DELETE("/files", s.driveDelete)
	driveAPI.POST("/upload", s.driveUpload)
	driveAPI.GET("/download", s.driveDownload)
	driveAPI.POST("/index/rebuild", s.driveUserIndexRebuild)
	driveAPI.GET("/index/status", s.driveUserIndexStatus)
	r.GET("/api/drive/preview", s.drivePreviewServe)

	r.GET("/api/mappings", s.listMappings)
	r.POST("/api/mappings", s.addMapping)
	r.PUT("/api/mappings/:id", s.updateMapping)
	r.DELETE("/api/mappings/:id", s.deleteMapping)
	r.POST("/api/mappings/one-click", s.oneClickMapping)

	cfGroup := r.Group("/api/cf", s.requireCF())
	cfGroup.GET("/zones", s.listZones)
	cfGroup.GET("/zones/:zoneId/records", s.listDNSRecords)
	cfGroup.POST("/zones/:zoneId/records", s.createDNSRecord)
	cfGroup.PUT("/zones/:zoneId/records/:recordId", s.updateDNSRecord)
	cfGroup.DELETE("/zones/:zoneId/records/:recordId", s.deleteDNSRecord)

	cfAccountGroup := r.Group("/api/cf/accounts")
	cfAccountGroup.GET("", s.listCFAccounts)
	cfAccountGroup.POST("", s.createCFAccount)
	cfAccountGroup.POST("/validate", s.validateCFAccount)
	cfAccountGroup.PUT("/:id", s.updateCFAccount)
	cfAccountGroup.DELETE("/:id", s.deleteCFAccount)
	cfAccountGroup.PUT("/:id/activate", s.activateCFAccount)

	r.GET("/api/ddns", s.listDDNS)
	r.POST("/api/ddns", s.addDDNS)
	r.PUT("/api/ddns/:id", s.updateDDNS)
	r.DELETE("/api/ddns/:id", s.deleteDDNS)
	r.GET("/api/ddns/ip", s.getPublicIP)

	r.GET("/api/stats", s.stats)
	r.GET("/api/system/volumes", s.getSystemVolumes)
	r.GET("/api/fs/browse", s.getFSBrowse)
	r.GET("/api/settings", s.getSettings)
	r.PUT("/api/settings", s.updateSettings)

	r.GET("/api/easytier/config", s.getEasyTierConfig)
	r.PUT("/api/easytier/config", s.putEasyTierConfig)
	r.GET("/api/easytier/profiles", s.listEasyTierProfiles)
	r.POST("/api/easytier/profiles", s.createEasyTierProfile)
	r.PUT("/api/easytier/profiles/:id", s.updateEasyTierProfile)
	r.DELETE("/api/easytier/profiles/:id", s.deleteEasyTierProfile)
	r.PUT("/api/easytier/profiles/active/:id", s.setEasyTierActiveProfile)
	r.GET("/api/easytier/profiles/:id/status", s.getEasyTierStatusByProfile)
	r.GET("/api/easytier/profiles/:id/version", s.getEasyTierVersionByProfile)
	r.GET("/api/easytier/profiles/:id/vpn-portal", s.getEasyTierVPNPortalByProfile)
	r.POST("/api/easytier/profiles/:id/daemon/start", s.postEasyTierDaemonStartByProfile)
	r.POST("/api/easytier/profiles/:id/daemon/stop", s.postEasyTierDaemonStopByProfile)
	r.POST("/api/easytier/profiles/:id/daemon/restart", s.postEasyTierDaemonRestartByProfile)
	r.GET("/api/easytier/profiles/:id/daemon/status", s.getEasyTierDaemonStatusByProfile)
	r.GET("/api/easytier/profiles/:id/daemon/logs", s.getEasyTierDaemonLogsByProfile)
	r.POST("/api/easytier/profiles/:id/daemon/release-port", s.postEasyTierDaemonReleasePortByProfile)
	r.GET("/api/easytier/status/all", s.getEasyTierStatuses)
	r.GET("/api/easytier/settings", s.getEasyTierSettings)
	r.PUT("/api/easytier/settings", s.updateEasyTierSettings)
	r.GET("/api/easytier/status", s.getEasyTierStatus)
	r.GET("/api/easytier/version", s.getEasyTierVersion)
	r.GET("/api/easytier/version/check", s.getEasyTierVersionCheck)
	r.GET("/api/easytier/vpn-portal", s.getEasyTierVPNPortal)
	r.GET("/api/easytier/platform", s.getEasyTierPlatform)
	r.GET("/api/easytier/releases", s.getEasyTierReleases)
	r.GET("/api/easytier/platforms", s.getEasyTierPlatforms)
	r.GET("/api/easytier/runtime/installed", s.getEasyTierRuntimeInstalled)
	r.GET("/api/easytier/runtime/list", s.getEasyTierRuntimeList)
	r.POST("/api/easytier/runtime/install", s.postEasyTierRuntimeInstall)
	r.DELETE("/api/easytier/runtime", s.deleteEasyTierRuntime)
	r.POST("/api/easytier/daemon/start", s.postEasyTierDaemonStart)
	r.POST("/api/easytier/daemon/stop", s.postEasyTierDaemonStop)
	r.POST("/api/easytier/daemon/restart", s.postEasyTierDaemonRestart)
	r.POST("/api/easytier/daemon/release-port", s.postEasyTierDaemonReleasePort)
	r.GET("/api/easytier/daemon/status", s.getEasyTierDaemonStatus)
	r.GET("/api/easytier/daemon/logs", s.getEasyTierDaemonLogs)

	r.GET("/api/webdav/mappings", s.listWebDavMappings)
	r.POST("/api/webdav/mappings", s.addWebDavMapping)
	r.PUT("/api/webdav/mappings/:id", s.updateWebDavMapping)
	r.DELETE("/api/webdav/mappings/:id", s.deleteWebDavMapping)
	r.POST("/api/webdav/mappings/:id/start", s.startWebDavMapping)
	r.POST("/api/webdav/mappings/:id/stop", s.stopWebDavMapping)
	r.POST("/api/webdav/mappings/:id/restart", s.restartWebDavMapping)
	r.GET("/api/webdav/mappings/:id/health", s.healthWebDavMapping)
	r.Any("/api/webdav/:id/*davPath", s.serveWebDAVByID)

	r.GET("/api/smb/mappings", s.listSMBMappings)
	r.POST("/api/smb/mappings/sync-local", s.syncLocalSMBMappings)
	r.POST("/api/smb/mappings", s.addSMBMapping)
	r.PUT("/api/smb/mappings/:id", s.updateSMBMapping)
	r.DELETE("/api/smb/mappings/:id", s.deleteSMBMapping)
	r.POST("/api/smb/mappings/:id/start", s.startSMBMapping)
	r.POST("/api/smb/mappings/:id/stop", s.stopSMBMapping)
	r.POST("/api/smb/mappings/:id/restart", s.restartSMBMapping)
	r.GET("/api/smb/mappings/:id/health", s.healthSMBMapping)
}
